# Generated by Django 2.1.1 on 2018-09-09 07:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lw2', '0002_auto_20180909_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='base_score',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lw2.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='posted_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='post',
            name='af',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='base_score',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='curated_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='frontpage_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='posted_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled (this should never appear)', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(max_length=17, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(max_length=17, primary_key=True, serialize=False),
        ),
    ]
