# Generated by Django 2.1.1 on 2018-09-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lw2', '0004_auto_20180909_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='trollolol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='html_body',
            field=models.TextField(default='<p>trololololol</p>'),
            preserve_default=False,
        ),
    ]
