# Generated by Django 2.1.1 on 2018-09-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lw2', '0015_profile_karma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
