# Generated by Django 2.1.1 on 2018-09-16 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lw2', '0016_auto_20180916_0310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='af',
        ),
        migrations.RemoveField(
            model_name='post',
            name='af',
        ),
        migrations.RemoveField(
            model_name='post',
            name='html_body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
