# Generated by Django 2.1.1 on 2018-09-26 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lw2', '0018_conversation_message_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posted_at']},
        ),
        migrations.AddField(
            model_name='profile',
            name='last_notifications_check',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
