# Generated by Django 2.1.1 on 2018-10-02 22:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lw2', '0022_auto_20180927_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=17)),
                ('type', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(default=datetime.datetime.today)),
                ('text', models.TextField(unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
