# Generated by Django 2.1.2 on 2018-12-19 08:34

from django.db import migrations
from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType

def make_groups(apps, schema_editor):
    mod_group = Group()
    mod_group.name = "moderators"
    mod_group.save()

    Post = apps.get_model('lw2','Post')
    Comment = apps.get_model('lw2', 'Comment')
    Tag = apps.get_model('lw2', 'Tag')
    Ban = apps.get_model('lw2', 'Ban')
    for content in (Post, Comment, Tag, Ban):
        ctype = ContentType.objects.get_for_model(content)
        mod_perm = Permission.objects.filter(content_type=ctype)
        for permission in mod_perm:
            if permission.codename.startswith("change"):
                next
            else:
                mod_group.permissions.add(permission)
    mod_group.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('lw2', '0024_auto_20181219_0950'),
    ]

    operations = [
        migrations.RunPython(make_groups),
    ]
