# Generated by Django 2.1.5 on 2019-02-16 06:28

from django.db import migrations, models
import lw2.models


class Migration(migrations.Migration):

    dependencies = [
        ('lw2', '0026_auto_20181230_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='curated_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='frontpage_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.TextField(validators=[lw2.models.validate_tag_text]),
        ),
    ]
